#Use § instead of & for write with colors
acPrefix: "§8[§4ADMINCHAT§8]" #This is how it will be in the chat/in the console: [ADMINCHAT] (with colors)
#With this prefix: /ac a -> [ADMINCHAT] {your name|console}: a

ac: "§c§lADMINCHAT>> "         #This is the prefix of the improper usage.
#This is how it will be in the chat/in the console: ADMINCHAT>>

nameColor: "§c "              #This is the color of your name in the adminchat
#If you set it to §c§l then your name is bold red (&c&l) in the adminchat

textColor: "§e"                #This is the color of text name in the adminchat
#If you set it to §e then your text is yellow (&e) in the adminchat

textSeparator: ": " #It is between the player's name and the textColor, spaces are required!

permission: "ac" #This permission will require to see messages
nonStaffUsage: true #If it is true, players can use this command without permission
permissionMessage: "§cYou have no permission to use this command!"

invalidUsage: "§cPlease provide a message!"
reloadSuccessfully: "§5Reload successfully"

#Help menu config
help:
  border: "§b+-------------------------+"
  usageCommand: "§b/ac usage §4» §aShow the usage."
  helpReloadCommand: "§b/ac reload §4» §aReload §6config.yml §avalues"
  usage: "§b/ac <message> §4» §aSend a message to the admin chat."