name: AdminChat
version: '1.0-RELEASE'
main: org.plugin.adminchat.AdminChat
api-version: 1.18
author: nl
commands:
  ac:
    description: Admin chat
    aliases:
      - adminchat
      - ac
      - helpop
      - ho
